const { contextBridge, ipcRenderer, webUtils } = require('electron');

const call = (ch, ...a) => ipcRenderer.invoke(ch, ...a).then(r => { if (!r.ok) throw new Error(r.error); return r.v; });
const on = (ch, fn) => { const l = (_, d) => fn(d); ipcRenderer.on(ch, l); return () => ipcRenderer.removeListener(ch, l); };

contextBridge.exposeInMainWorld('api', {
  getSettings: () => call('settings:get'),
  setSettings: p => call('settings:set', p),
  themes: () => call('themes:list'),
  scan: () => call('library:scan'),
  update: (id, patch) => call('library:update', id, patch),
  markWatched: (id, v) => call('library:markWatched', id, v),
  markEpisode: (id, f, v) => call('library:markEpisode', id, f, v),
  reveal: id => call('library:reveal', id),
  searchCovers: (t, y, k) => call('cover:search', t, y, k),
  applyCover: (id, c) => call('cover:apply', id, c),
  autoCover: id => call('cover:auto', id),
  renameFiles: dry => call('library:renameFiles', dry),
  autoMeta: (id, force) => call('meta:auto', id, force),
  coverFromFile: (id, f) => call('cover:fromFile', id, f),
  coverFromUrl: (id, u) => call('cover:fromUrl', id, u),
  removeCover: id => call('cover:remove', id),
  pickImage: () => call('dialog:pickImage'),
  pickFolder: () => call('dialog:pickFolder'),
  play: (id, file, pos) => call('play', id, file, pos),
  iaSearch: (q, f) => call('ia:search', q, f),
  iaFiles: id => call('ia:files', id),
  iaDownload: (id, file, title, info, ghostId) => call('ia:download', id, file, title, info, ghostId),
  appVersion: () => call('app:version'),
  updateCheck: () => call('update:check'),
  updateDownload: () => call('update:download'),
  updateInstall: () => call('update:install'),
  onUpdate: fn => on('update:event', fn),
  playerSpec: () => call('binds:playerSpec'),
  audioDevices: () => call('audio:devices'),
  testAudio: dev => call('audio:test', dev),
  addGhost: d => call('library:addGhost', d),
  deleteFiles: (id, permanent) => call('library:delete', id, permanent),
  forget: id => call('library:forget', id),
  iaCancel: id => call('ia:cancel', id),
  openThemes: () => call('app:openThemes'),
  openData: () => call('app:openData'),
  openExternal: u => call('app:openExternal', u),
  setFullscreen: v => call('app:fullscreen', v),
  quit: () => call('app:quit'),
  pathForFile: f => webUtils.getPathForFile(f),
  onProgress: fn => on('ia:progress', fn),
  onPlayer: fn => on('player:state', fn),
  onChanged: fn => on('library:changed', fn),
});
